env:
  global:
  - REPO=d1ablorus/rancher-xe-guest-utils
  - TAG=v7.0.0-24

services:
  - docker

script:
  - docker run --rm -w /tmp -v $(PWD)/dist:/dist -v $(PWD)/assets:/assets:ro iron/go:dev sh /assets/build.sh
  - docker build -t $REPO .;
  - docker tag $REPO:latest $REPO:$TAG;
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $REPO;
  - docker push $REPO:$TAG;
